name: "Build and push typescript sdk"

on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - idn/**

jobs:
  push_spec_workflow:
    name: Build and push typescript SDK
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Checkout the main branch of api-specs
      - name: Checkout API Specs Repo
        uses: actions/checkout@v2
        with:
          repository: sailpoint-oss/sdk-ts
          path: sdk-ts
          ref: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Build V3 SDK
        run: |
          cd sdk-ts
          pwd
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.v3.yaml -g typescript-axios -o sdk-output/v3 --global-property skipFormModel=false --config sdk-resources/v3-config.yaml --api-name-suffix V3 --model-name-suffix V3

      - name: Build Beta SDK
        run: |
          cd sdk-ts
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.beta.yaml -g typescript-axios -o sdk-output/beta --global-property skipFormModel=false --config sdk-resources/beta-config.yaml --api-name-suffix Beta --model-name-suffix Beta

      - name: After SDK Build
        run: |
          cd sdk-ts
          git status