name: "Build and push go sdk"

on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - idn/**

jobs:
  push_spec_workflow:
    name: Build and push Go SDK
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Checkout the main branch of api-specs
      - name: Checkout API Specs Repo
        uses: actions/checkout@v2
        with:
          repository: sailpoint-oss/golang-sdk
          path: golang-sdk
          ref: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build V3 SDK
        id: buildV3
        run: |
          cd golang-sdk
          pwd
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.v3.yaml -g go -o sdk-output/v3 --global-property skipFormModel=false --config sdk-resources/v3-config.yaml -p enumClassPrefix=true
          
      - name: Build Beta SDK
        id: buildBeta
        if: steps.buildV3.outcome == 'success'
        run: |
          cd golang-sdk
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.beta.yaml -g go -o sdk-output/beta --global-property skipFormModel=false --config sdk-resources/beta-config.yaml -p enumClassPrefix=true

      - name: After SDK Build
        if: steps.buildBeta.outcome == 'success'
        run: |
          cd golang-sdk/sdk-resources
          node postscript.js
          cd ..

          git config --unset-all http.https://github.com/.extraheader
          git config --local user.email "tyler.mairose@sailpoint.com"
          git config --local user.name "GitHub Action Bot"

          git add .
          git commit -m "Automated build of go sdk: ${{ github.run_id }}"

          git status

          git remote set-url origin https://${{secrets.API_SPEC_PAT}}@github.com/sailpoint-oss/golang-sdk.git

          git remote -v