name: "Build and push typescript sdk"

on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - idn/**

jobs:
  push_spec_workflow:
    name: Build and push typescript SDK
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Checkout the main branch of api-specs
      - name: Checkout API Specs Repo
        uses: actions/checkout@v3
        with:
          repository: sailpoint-oss/sdk-ts
          path: sdk-ts
          ref: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Build V3 SDK
        id: buildV3
        run: |
          cd sdk-ts
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.v3.yaml -g typescript-axios -o sdk-output/v3 --global-property skipFormModel=false --config sdk-resources/v3-config.yaml

      - name: Build Beta SDK
        id: buildBeta
        if: steps.buildV3.outcome == 'success'
        run: |
          cd sdk-ts
          java -jar openapi-generator-cli.jar generate -i ../idn/sailpoint-api.beta.yaml -g typescript-axios -o sdk-output/beta --global-property skipFormModel=false --config sdk-resources/beta-config.yaml --api-name-suffix BetaApi --model-name-suffix Beta

      - name: Run npm install and build Typescript SDK
        id: buildSDK
        if: steps.buildBeta.outcome == 'success'
        run: |
          cd sdk-ts/sdk-output
          npm install
          npm run build
      
      - name: After SDK Build
        if: steps.buildSDK.outcome == 'success'
        run: |
          cd sdk-ts

          git config --unset-all http.https://github.com/.extraheader
          git config --local user.email "tyler.mairose@sailpoint.com"
          git config --local user.name "GitHub Action Bot"

          git add .
          git commit -m "Automated build of typescript-axios sdk: ${{ github.run_id }}"

          git status

          git remote set-url origin https://${{secrets.API_SPEC_PAT}}@github.com/sailpoint-oss/sdk-ts.git

          git remote -v